### ISSUE TITLE
Retrofit 2.0 JSON Query functionality

### ISSUE THREAD

**Issue by Aeonitis** [Aeonitis/LH-Android#13]
Troubleshooting 404 on query:

Code in interface
`@GET("/user/lookup/{userID}")`
`Call<ResponseBody> getJSONString(@Path("userID") String userID);`

Impl. Code and error logs
![issue retrofit](https://cloud.githubusercontent.com/assets/1273824/13381655/43dae6cc-de59-11e5-8a7d-9aea7c87f599.png)

**Comment by Aeonitis** [comment]
Confusion at the headquarters https://github.com/square/retrofit/issues/1222

**Comment by Aeonitis** [comment]
`- Base URL: always ends with /`
`- @Url: DO NOT start with /`

Source: http://inthecheesefactory.com/blog/retrofit-2.0/en

**Comment by Aeonitis** [comment]
`FATAL EXCEPTION: main
                                                                Process: com.lh.android, PID: 18051
                                                                java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                    at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:275)
                                                                    at android.view.View.performClick(View.java:4856)
                                                                    at android.view.View$PerformClick.run(View.java:19956)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:211)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5373)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:270)
                                                                    at android.view.View.performClick(View.java:4856) 
                                                                    at android.view.View$PerformClick.run(View.java:19956) 
                                                                    at android.os.Handler.handleCallback(Handler.java:739) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                    at android.os.Looper.loop(Looper.java:211) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5373) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
                                                                 Caused by: java.lang.IllegalArgumentException: URL query string "userID={userID}" must not have replace block. For dynamic query parameters use @Query.
                                                                    for method LHRESTService.getJSONString
                                                                    at retrofit2.Utils.methodError(Utils.java:119)
                                                                    at retrofit2.Utils.methodError(Utils.java:109)
                                                                    at retrofit2.RequestFactoryParser.parseHttpMethodAndPath(RequestFactoryParser.java:177)
                                                                    at retrofit2.RequestFactoryParser.parseMethodAnnotations(RequestFactoryParser.java:106)
                                                                    at retrofit2.RequestFactoryParser.parse(RequestFactoryParser.java:64)
                                                                    at retrofit2.MethodHandler.create(MethodHandler.java:34)
                                                                    at retrofit2.Retrofit.loadMethodHandler(Retrofit.java:164)
                                                                    at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
                                                                    at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                                    at $Proxy0.getJSONString(Unknown Source)
                                                                    at com.lh.android.MainActivity.postScanforString(MainActivity.java:230)
                                                                    at com.lh.android.MainActivity.onBtnScanClick(MainActivity.java:166)
                                                                    	... 13 more`

![issue retrofit 2](https://cloud.githubusercontent.com/assets/1273824/13381897/2aadbef8-de5f-11e5-88df-43df5c55bc10.png)

**Comment by Aeonitis** [comment]
This code brings up the same error as above too
`@GET("http://192.168.0.28:8080/user/lookup?userID={userID}")
    Call<ResponseBody> getJSONString(@Path("userID") String userID);`

**Comment by Aeonitis** [comment]
Resolved:
![issue retrofit 3](https://cloud.githubusercontent.com/assets/1273824/13382055/27ccea02-de63-11e5-9a75-dd7414e497fc.png)
