### ISSUE TITLE
RuntimeException: API key not in the <application> element of AndroidManifest.xml

### ISSUE THREAD

**Issue by Aeonitis** [Aeonitis/LH-Android#5]
`AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.lh.android, PID: 6210
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lh.android/com.lh.android.MainActivity}: android.view.InflateException: Binary XML file line #12: Error inflating class fragment
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:156)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                  at android.os.Looper.loop(Looper.java:211)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5373)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                               Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class fragment
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257)
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                  at com.lh.android.MainActivity.onCreate(MainActivity.java:22)
                                                                  at android.app.Activity.performCreate(Activity.java:5990)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442) 
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:156) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:211) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5373) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
                                                               Caused by: java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
                                                                  at com.google.maps.api.android.lib6.c.ad.a(Unknown Source)
                                                                  at com.google.maps.api.android.lib6.a.e.a(Unknown Source)
                                                                  at com.google.android.gms.maps.internal.CreatorImpl.b(Unknown Source)
                                                                  at com.google.android.gms.maps.internal.CreatorImpl.b(Unknown Source)
                                                                  at com.google.android.gms.maps.internal.h.onTransact(SourceFile:62)
                                                                  at android.os.Binder.transact(Binder.java:380)
                                                                  at com.google.android.gms.maps.internal.ah.b(SourceFile:179)
                                                                  at com.google.android.gms.maps.internal.CreatorImpl.b(SourceFile:100)
                                                                  at com.google.android.gms.maps.internal.ag.onTransact(SourceFile:62)
                                                                  at android.os.Binder.transact(Binder.java:380)
                                                                  at com.google.android.gms.maps.internal.zzc$zza$zza.zzs(Unknown Source)
                                                                  at com.google.android.gms.maps.MapFragment$zzb.zzzW(Unknown Source)
                                                                  at com.google.android.gms.maps.MapFragment$zzb.zza(Unknown Source)
                                                                  at com.google.android.gms.dynamic.zza.zza(Unknown Source)
                                                                  at com.google.android.gms.dynamic.zza.onInflate(Unknown Source)
                                                                  at com.google.android.gms.maps.MapFragment.onInflate(Unknown Source)
                                                                  at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2115)
                                                                  at android.app.Activity.onCreateView(Activity.java:5328)
                                                                  at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:34)
                                                                  at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:79)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:257) 
                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                  at com.lh.android.MainActivity.onCreate(MainActivity.java:22) 
                                                                  at android.app.Activity.performCreate(Activity.java:5990) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442) 
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:156) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:211) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5373) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) `

**Comment by Aeonitis** [comment]
Resolved by 6c4b2aa
